### ISSUE TITLE
Ocaml-seq-utils vs (c-cube's) Oseq

### ISSUE THREAD

**Issue by Fourchaux** [darrenldl/ocaml-seq-utils#1]
Why not contribute directly to c-cube's Oseq library?
Many functions seem to be duplicated, right?

https://github.com/c-cube/oseq

**Comment by darrenldl** [comment]
Thanks for pointing it to me - I only searched "seq" on opam and didn't find a similar one so didn't think twice in creating this, or I missed it accidentally.

There's literally no reason I'd have created this had I known about OSeq.

OSeq looks very complete, so I'll just make a PR to add the number sequences I think.

Thanks again for letting me know!

EDIT: Right yep searching "seq" on opam shows "oseq" alright - I must have missed it, silly me.
